[plugin-info]
## To modify by developper(s) of the plugin
SHORT_PLUGIN_NAME = 'piezosystemjena'
package-url = 'https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena'
description = 'Pymodaq Plugin for the Control of Piezosystem Jena microscopy stages'

author = 'Nicolas Tappy'
author-email = 'nicolas.tappy@epfl.ch'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyserial']
